[product]
name = "Chair"
type = "assembly"

[parameters.back-height]
short-id = "bh"
label = "Back height"
description = "The height from the seat to the top of the backrest"
type = "number"
min = 5
max = 10
step = 5

[parameters.seat-depth]
short-id = "sd"
label = "Seat Depth"
type = "number"
min = 5
max = 15

[parameters.seat-height]
short-id = "sh"
label = "Seat Height"
description = "The height from the ground to the top of the seat"
type = "number"
min = 5
max = 15

[parameters.seat-width]
short-id = "sw"
label = "Seat Width"
type = "number"
min = 5
max = 10
step = 5

[parameters.should-include-back]
short-id = "b"
label = "Include back"
type = "boolean"

[presets.regular]
label = "Regular (Without Back)"
back-height = 10
seat-depth = 10
seat-height = 10
seat-width = 10
should-include-back = false

[presets.regular-with-back]
label = "Regular (With Back)"
back-height = 10
seat-depth = 10
seat-height = 10
seat-width = 10
should-include-back = true
