name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
        with:
          setup-cache-only: 'true'

  build:
    runs-on: ubuntu-latest
    needs: pnpm
    strategy:
      matrix:
        task: [deps, lint, test, 'test:pkg']

    name: ${{ matrix.task }}
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm
      - uses: ./.github/actions/setup-turbo

      - name: Run ${{ matrix.task }}
        run: pnpm run ${{ matrix.task }} ${{ env.CLI_ARGS }}
        env:
          FORCE_COLOR: 1
