name: Release

on:
  push:
    # temporary
    branches: ["tidy-meta"]
    tags: ['*']
  workflow_dispatch:

jobs:
  studio:
    name: release-studio

    runs-on: [ubuntu-22.04, windows-2022, macos-12]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the commit
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup turbo cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: npm install

      - name: Builds workspace packages
        run: FORCE_COLOR=1 npm run build:pkg

      - name: Package, make, and publish studio app
        run: FORCE_COLOR=1 npm run -w '@villagekit/studio' publish
